services:
  christian:
    container_name: christian
    environment:
      - PYTHONUNBUFFERED=1

      - SERVICE_PORT=${SERVICE_PORT:-5000}
      - API_TOKEN=${API_TOKEN:-placeholder}
      - DASHBOARD_HOSTNAME=${DASHBOARD_HOSTNAME:-placeholder}
      - TURNI_HOSTNAME=${TURNI_HOSTNAME:-placeholder}
      - TURNI_PORT=${TURNI_PORT:-5000}
      - MEALIE_HOSTNAME=${MEALIE_HOSTNAME:-placeholder}
      - MEALIE_PORT=${MEALIE_PORT:-5000}
      - MEALIE_TOKEN=${MEALIE_TOKEN:-placeholder}
      - SUBSCRIBERS_FILE=${SUBSCRIBERS_FILE:-placeholder}
    ports:
      - "8759:${SERVICE_PORT}"
    restart: unless-stopped
    build: .
    pull_policy: build