services:
  christian:
    container_name: christian
    environment:
      - PYTHONUNBUFFERED=1

      - SERVICE_PORT=${SERVICE_PORT:-5000}

      - API_TOKEN=${API_TOKEN:-placeholder}

      - DASHBOARD_HOSTNAME=${DASHBOARD_HOSTNAME:-placeholder}

      - TURNI_HOSTNAME=${TURNI_HOSTNAME:-placeholder}
      - TURNI_PORT=${TURNI_PORT:-5000}

      - MEALIE_HOSTNAME=${MEALIE_HOSTNAME:-placeholder}
      - MEALIE_PORT=${MEALIE_PORT:-5000}
      - MEALIE_TOKEN=${MEALIE_TOKEN:-placeholder}
      
      - SUBSCRIBERS_FILE=${SUBSCRIBERS_FILE:-placeholder}
      
      - HOME_ASSISTANT_HOSTNAME=${HOME_ASSISTANT_HOSTNAME:-placeholder}
      - HOME_ASSISTANT_PORT=${HOME_ASSISTANT_PORT:-placeholder}
      - HOME_ASSISTANT_TOKEN=${HOME_ASSISTANT_TOKEN:-placeholder}
      - ID_LAVATRICE=${ID_LAVATRICE:-placeholder}

      - SUBSCRIBERS_LAVATRICE_FILE=${SUBSCRIBERS_LAVATRICE_FILE}

      - FLASK_APP=app.py
      - FLASK_DEBUG=${FLASK_DEBUG:-True}
      - FLASK_HOST=${FLASK_HOST:-0.0.0.0}
      - FLASK_PORT=${FLASK_PORT:-5000}
    ports:
      - "8759:${FLASK_PORT}"
    restart: unless-stopped
    build: .
    pull_policy: build